refactor(game-stats): initial setup for game-stats and badge
refactors made:

1) game-stats's workspaces
- setup drafts of packages (game-stats-schema & game-stats-types)
- setup draft of the microservice (game-stats)

2) badge
- extract it from profile-type, as its own type (badge-types)
- easily imported by both profile(displayed badge)
  & game-stats(unlocked badges)
- add as dependencies(package.json) &
  within references array(tsconfig.json)

3) other minor refactorings
- docker compose:
  - increase readability in additional contexts with alignments
- comments:
  - remove anything related with postgres 18.
  - decided to stick with the current version used, 17-bookworm.
  - no urgency or heavy needs require upgrading to postgres 18.

diff --git a/services/game-stats/Dockerfile b/services/game-stats/Dockerfile
--- a/services/game-stats/Dockerfile
+++ b/services/game-stats/Dockerfile
@@ -2,56 +2,53 @@
 FROM node:20-alpine AS builder
 WORKDIR /app
 
-COPY package*.json ./
-COPY packages/postgres/auth-schema/package.json ./packages/postgres/auth-schema/
-COPY packages/types/badge-types/package.json ./packages/types/badge-types/
-COPY packages/types/game-stats-types/package.json ./packages/types/game-stats-types/
-COPY packages/postgres/game-stats-schema/package.json ./packages/postgres/game-stats-schema/
-COPY packages/postgres/postgres-client/package.json ./packages/postgres/postgres-client/
-COPY services/game-stats/package.json ./services/game-stats/
+COPY --from=postgres-client     package.json    ./packages/postgres/postgres-client/
+COPY --from=auth-schema         package.json    ./packages/postgres/auth-schema/
+COPY --from=badge-types         package.json    ./packages/types/badge-types/
+COPY --from=game-stats-types    package.json    ./packages/types/game-stats-types/
+COPY --from=game-stats-schema   package.json    ./packages/postgres/game-stats-schema/
+COPY                            package.json    ./services/game-stats/
+COPY --from=root                package*.json   ./
 
 RUN npm ci
 
 COPY . .
 
-RUN npm run --prefix packages/postgres/auth-schema build
-RUN npm run --prefix packages/types/badge-types build
-RUN npm run --prefix packages/types/game-stats-types build
-RUN npm run --prefix packages/postgres/game-stats-schema build
-RUN npm run --prefix packages/postgres/postgres-client build
-RUN npm run --prefix services/game-stats build
+RUN npm run build:docker -w game-stats
 
 #Runner
 FROM node:20-alpine AS runner
 WORKDIR /app
 
-COPY package*.json ./
-COPY packages/postgres/auth-schema/package.json ./packages/postgres/auth-schema/
-COPY packages/types/badge-types/package.json ./packages/types/badge-types/
-COPY packages/types/game-stats-types/package.json ./packages/types/game-stats-types/
-COPY packages/postgres/game-stats-schema/package.json ./packages/postgres/game-stats-schema/
-COPY packages/postgres/postgres-client/package.json ./packages/postgres/postgres-client/
-COPY services/game-stats/package.json ./services/game-stats/
-
-RUN apk update && \
-    apk add --no-cache curl && \
-    rm -rf /var/cache/apk/*
+COPY --from=postgres-client     package.json    ./packages/postgres/postgres-client/
+COPY --from=auth-schema         package.json    ./packages/postgres/auth-schema/
+COPY --from=badge-types         package.json    ./packages/types/badge-types/
+COPY --from=game-stats-types    package.json    ./packages/types/game-stats-types/
+COPY --from=game-stats-schema   package.json    ./packages/postgres/game-stats-schema/
+COPY                            package.json    ./services/game-stats/
+COPY --from=root                package*.json   ./
 
 ENV NODE_ENV=production
 RUN npm ci --omit=dev
 
-COPY --from=builder /app/packages/postgres/auth-schema/dist ./packages/postgres/auth-schema/dist
-COPY --from=builder /app/packages/types/badge-types/dist ./packages/types/badge-types/dist
-COPY --from=builder /app/packages/types/game-stats-types/dist ./packages/types/game-stats-types/dist
-COPY --from=builder /app/packages/postgres/game-stats-schema/dist ./packages/postgres/game-stats-schema/dist
-COPY --from=builder /app/packages/postgres/postgres-client/dist ./packages/postgres/postgres-client/dist
-COPY --from=builder /app/services/game-stats/dist ./services/game-stats/dist
+COPY --from=builder /app/packages/postgres/postgres-client/dist     ./packages/postgres/postgres-client/dist
+COPY --from=builder /app/packages/postgres/auth-schema/dist         ./packages/postgres/auth-schema/dist
+COPY --from=builder /app/packages/types/badge-types/dist            ./packages/types/badge-types/dist
+COPY --from=builder /app/packages/types/game-stats-types/dist       ./packages/types/game-stats-types/dist
+COPY --from=builder /app/packages/postgres/game-stats-schema/dist   ./packages/postgres/game-stats-schema/dist
+COPY --from=builder /app/services/game-stats/dist                   ./services/game-stats/dist
 
-EXPOSE 3000
+COPY scripts/* /usr/local/bin
 
-COPY services/game-stats/scripts/game-stats-entrypoint.sh /usr/local/bin/entrypoint.sh
-RUN chmod +x /usr/local/bin/entrypoint.sh
+ENV PORT=3000
+# ^ default fallback only, in case someone runs this image standalone without Compose.
+# Compose's `environment: PORT=${FRIENDS_SERVICE_PORT}` overrides this ENV at runtime.
+
+EXPOSE ${PORT}
+
+# HEALTHCHECK --interval=5s --timeout=3s --retries=3 --start-period=5s \
+# 	CMD wget -q --spider http://localhost:${PORT}/health || exit 1
 
 WORKDIR /app/services/game-stats
-ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
+ENTRYPOINT ["/usr/local/bin/game-stats-entrypoint.sh"]
 CMD ["npm", "run", "start"]
